1. Import NumPy and create a NumPy array using the list
[10, 20, 30, 40, 50]
Print the array.

In [ ]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


2. Create a NumPy array containing numbers from 1 to 15.

In [ ]:
arr1 = np.arange(1,16)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


3. Create the following arrays:
a) An array of 6 zeros
b) An array of 6 ones

In [ ]:
zeros_arr = np.zeros(6)
print(zeros_arr)

ones_arr = np.ones(6)
print(ones_arr)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


4. Create a NumPy array [5, 10, 15, 20] and print:
a) Data type of the array
b) Shape of the array

In [ ]:
array = np.array([5,10,15,20])
print(array.dtype)
print(array.shape)

int64
(4,)


5. From the array [100, 200, 300, 400, 500]:
a) Print the first element
b) Print the last element

In [ ]:
new_arr = np.array([100,200,300,400,500])
print(new_arr[0])
print(new_arr[-1])

6. Given the array [10, 20, 30, 40, 50], extract the sub-array
[20, 30, 40].

In [ ]:
array = np.array([10,20,30,40,50])
sub_array = array[1:-1]
print(sub_array)

7. From the array [5, 15, 25, 35, 45], print all elements except the first and last.

In [ ]:
array = np.array([5,15,25,35,45])
i = 0
while i < len(array):
  if (i == 0) or (i == len(array)-1):
     i += 1
     continue
  else:
    print(array[i])
  i += 1

15
25
35


8. Create a NumPy array of 10 even numbers using arange().

In [ ]:
array = np.arange(2,22,2)
print(array)

9. Add 5 to each element of the array
[2, 4, 6, 8].

In [ ]:
array = np.array([2,4,6,8])
print(array+5)

[ 7  9 11 13]


10. Multiply all elements of the array
[3, 6, 9, 12]
by 2.

In [ ]:
array = np.array([3,6,9,12])
print(array*2)

[ 6 12 18 24]


11. Find the square of each element in the array [1, 2, 3, 4, 5].


In [ ]:
array = np.array([1,2,3,4,5])
squared_array = np.array([i*i for i in array])
print(squared_array)

[ 1  4  9 16 25]


12. Create two arrays
[10, 20, 30]
[5, 10, 15]
Perform element-wise addition and subtraction.

In [16]:
array1 = np.array([10,20,30])
array2 = np.array([5,10,15])

addition = array1 + array2
subtraction = array1 - array2

print(array1,"\n",array2, sep="")

[10 20 30]
[ 5 10 15]


13. From the array [12, 67, 45, 89, 34], print values greater than 50.

In [19]:
array = np.array([12,67,45,89,34])
print(array[array > 50])

[67 89]


14. Replace all negative values in the array
[4, -2, 7, -9, 3]
with 0.

In [21]:
array = np.array([4,-2,7,-9,3])
array[array < 0] = 0
print(array)

[4 0 7 0 3]


15. Given student marks
[35, 78, 90, 45, 60],
count how many students passed (pass mark = 40).

In [22]:
array = np.array([35,78,90,45,60])
count = len(array[array >= 40])
print("Total student passed: ", count)

Total student passed:  4


16. Given monthly expenses
[1200, 2500, 5000, 800, 4300],
replace values greater than 4000 with 4000.

In [27]:
expenses = [1200,2500,5000,800,4300]
array = np.array(expenses)
array[array > 4000] = 4000
print(array)

[1200 2500 4000  800 4000]


17. Convert the following temperatures from Celsius to Fahrenheit:
[0, 20, 30, 40].

In [28]:
array = np.array([0,20,30,40])
new_array = 9/5*array + 32
print(new_array)

[ 32.  68.  86. 104.]


18. Given salaries
[25000, 32000, 40000, 28000],
add a bonus of 2000 to salaries greater than 30000.

In [35]:
array = np.array([25000,32000,40000,28000])
array[array > 30000] += 2000
print(array)

[25000 34000 42000 28000]


19. Square only the positive numbers in the array
[2, -3, 4, -5, 6]

In [44]:
array = np.array([2,-3,4,-5,6])
positive_squared = np.array([i*i for i in array if i > 0])
print(positive_squared)

[ 4 16 36]
